spring.application.name=gastrowebapp


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/food_delivery_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:your_mysql_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


server.port=8080


app.jwt.secret=${JWT_SECRET:ThisIsMyVeryLongSecretKeyForJwtAuthentication123456789}
app.jwt.expiration=${JWT_EXPIRATION:86400000}


razorpay.key.id=${RAZORPAY_KEY_ID:your-key-id}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:your-key-secret}


app.order.delivery-fee=40.00

app.order.tax-amount=25.00

